// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_vWEEQZkIECSb9vDQDY1udno--BHwhs',
    appId: '1:878574192058:web:daf7772fb5363514bd0983',
    messagingSenderId: '878574192058',
    projectId: 'taskufuture-ab137',
    authDomain: 'taskufuture-ab137.firebaseapp.com',
    storageBucket: 'taskufuture-ab137.appspot.com',
    measurementId: 'G-DERGKEWYXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTE0WZrN_OyiDfd6WGmOatGo-krV2eSfQ',
    appId: '1:878574192058:android:d0304a30db8d5dffbd0983',
    messagingSenderId: '878574192058',
    projectId: 'taskufuture-ab137',
    storageBucket: 'taskufuture-ab137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9JiEJS9R3PyvzMWvV-bM2pL4-HjqaEHc',
    appId: '1:878574192058:ios:8cb35b80d2812d19bd0983',
    messagingSenderId: '878574192058',
    projectId: 'taskufuture-ab137',
    storageBucket: 'taskufuture-ab137.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9JiEJS9R3PyvzMWvV-bM2pL4-HjqaEHc',
    appId: '1:878574192058:ios:8cb35b80d2812d19bd0983',
    messagingSenderId: '878574192058',
    projectId: 'taskufuture-ab137',
    storageBucket: 'taskufuture-ab137.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_vWEEQZkIECSb9vDQDY1udno--BHwhs',
    appId: '1:878574192058:web:fcb370e4e0156634bd0983',
    messagingSenderId: '878574192058',
    projectId: 'taskufuture-ab137',
    authDomain: 'taskufuture-ab137.firebaseapp.com',
    storageBucket: 'taskufuture-ab137.appspot.com',
    measurementId: 'G-FTDS9K9NYJ',
  );
}
